name: deploy

on:
  push:
    branches:
      - master

jobs:
  ci:
    name: Run deploy
    runs-on: ubuntu-latest
    steps:
      # 해당 저장소의 코드를 가져옵니다.
      - name: Git checkout
        uses: actions/checkout@v3

      # node를 설치합니다.
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # node_modules 캐싱을 이용합니다.
      - name: Cache yarn dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # 패키지를 설치합니다.
      - name: Install dependencies
        run: yarn install

      # CRA build
      - name: Build CRA
        run: yarn build
